apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app2
  namespace: openshift-gitops
spec:
  destination:
    namespace: bubble-animation2
    server: https://kubernetes.default.svc 
  project: default
  source: 
    path: bubble-animation/application-mainfest
    repoURL: https://github.com/gadikotamohan/argocd-apps
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
