apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bubble-animation2
  name: bubble-animation2
  namespace: bubble-animation2
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bubble-animation2
    weight: 100
